[server]
host = "localhost"
port = 8088

[mappings.italy-account-api]
host = "http://feeds.williamhill-swi.com/mobenga_demo23/italy/account-api/rest"

[mappings.italy-sport-api]
host = "http://feeds.williamhill-swi.com/mobenga_demo23/italy/sport-api/rest"

[mappings.italy-session-api]
host = "http://feeds.williamhill-swi.com/mobenga_demo23/italy/session-api/rest"

[mappings.italy-payment-api]
host = "http://feeds.williamhill-swi.com/mobenga_demo23/italy/payment-api/rest"

[mappings.spain-account-api]
host = "http://feeds.williamhill-swi.com/mobenga_demo23/spain/account-api/rest"

[mappings.spain-sport-api]
host = "http://feeds.williamhill-swi.com/mobenga_demo23/spain/sport-api/rest"

[mappings.spain-session-api]
host = "http://feeds.williamhill-swi.com/mobenga_demo23/spain/session-api/rest"

[mappings.spain-payment-api]
host = "http://feeds.williamhill-swi.com/mobenga_demo23/spain/payment-api/rest"